import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ReactQueryProviders from "@/hooks/useReactQuery";

const inter = Inter({ subsets: ["latin"] });

export const metdata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProviders>
        <body className={inter.className}>{children}</body>
      </ReactQueryProviders>
    </html>
  );
}
